# Netlify Konfigürasyonu
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Netlify Functions ayarları
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cloudinary"]
  included_files = ["server/**/*"]

# API route'ları için redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/*"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers - Security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Headers - API cache control
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"